--liquibase formatted sql

--changeset thorold:1
CREATE TABLE population
(
    id           INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pop_alliance INT NOT NULL DEFAULT 0,
    pop_horde     INT NOT NULL DEFAULT 0
);
CREATE TABLE server
(
    id          INT PRIMARY KEY,
    name        VARCHAR(32) NOT NULL,
    region      VARCHAR(3)  NOT NULL,
    faction     VARCHAR(32) NOT NULL,
    type        VARCHAR(6)  NOT NULL,
    population_id INT REFERENCES population (id),
    unique_name VARCHAR(64) GENERATED ALWAYS AS ( REPLACE(REPLACE(LOWER(name), ' ', '-'), '''', '') || '-' ||
                                                  LOWER(faction)) STORED
);

CREATE TABLE server_price
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    server_id    INT           NOT NULL REFERENCES server (id),
    value        DECIMAL(7, 6) NOT NULL,
    currency     VARCHAR(4)    NOT NULL,
    last_updated TIMESTAMP     NOT NULL
);


CREATE TABLE item
(
    id             INT PRIMARY KEY,
    quality        VARCHAR(32)  NOT NULL,
    type           VARCHAR(32)  NOT NULL,
    name           VARCHAR(255) NOT NULL,
    icon           VARCHAR(255) NOT NULL,
    sell_price     BIGINT,
    required_level INT,
    item_level     INT,
    item_link      VARCHAR(255),
    unique_name    VARCHAR(64)  NOT NULL
)
