name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test

      - name: Build and Push Docker Image
        run:
          ./gradlew jib -Djib.to.image=registry.hub.docker.com/thorold/economatic -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }}
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}